// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaF2wiOhus7rhzDRGyL8qLcWghT_OoEEg',
    appId: '1:45651594992:web:a9eb97c82ebffe0be77c35',
    messagingSenderId: '45651594992',
    projectId: 'fullapp-2a204',
    authDomain: 'fullapp-2a204.firebaseapp.com',
    storageBucket: 'fullapp-2a204.firebasestorage.app',
    measurementId: 'G-PYGV0LVZT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbzjusdVP4yOIZmMqZbz3Hwc6YZ5mm23Y',
    appId: '1:45651594992:android:81a6c73a1d162dd3e77c35',
    messagingSenderId: '45651594992',
    projectId: 'fullapp-2a204',
    storageBucket: 'fullapp-2a204.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLDY3FiU72wwSE50pwP3qM3xXLmEqGpmA',
    appId: '1:45651594992:ios:19c4923fedb2364fe77c35',
    messagingSenderId: '45651594992',
    projectId: 'fullapp-2a204',
    storageBucket: 'fullapp-2a204.firebasestorage.app',
    iosBundleId: 'com.example.cvProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLDY3FiU72wwSE50pwP3qM3xXLmEqGpmA',
    appId: '1:45651594992:ios:19c4923fedb2364fe77c35',
    messagingSenderId: '45651594992',
    projectId: 'fullapp-2a204',
    storageBucket: 'fullapp-2a204.firebasestorage.app',
    iosBundleId: 'com.example.cvProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaF2wiOhus7rhzDRGyL8qLcWghT_OoEEg',
    appId: '1:45651594992:web:cf9d0076229ceb61e77c35',
    messagingSenderId: '45651594992',
    projectId: 'fullapp-2a204',
    authDomain: 'fullapp-2a204.firebaseapp.com',
    storageBucket: 'fullapp-2a204.firebasestorage.app',
    measurementId: 'G-DBMLH9BMT8',
  );
}
